### ISSUE TITLE
Merkle Tree: Fragmentation of files

### ISSUE THREAD

**Issue by Kleissner** [PeernetOfficial/core#48]
Add a feature to fragment files into chunks similar to how torrents work.

Currently only the hash of the entire file is stored on the blockchain.
The file record type on the blockchain supports metadata tags, we can use that to create a new tag "file fragments" which will be a list of hashes for each fragment.

We can look into the implementation of torrent clients and directly into .torrent files what common fragmentation strategies are.

The code to store the fragment hashes (or just the merkle tree?!) will go here: https://github.com/PeernetOfficial/core/blob/master/blockchain/Block%20Record%20File.go

**Merkle Tree**

Torrent files support a merkle tree: https://en.wikipedia.org/wiki/Torrent_file#Merkle_trees
Do we want that? In that case only the root hash needs to be stored.

We probably should just do some calculations to see how large files (that could be even up to TBs) would impact that file record size. We have a soft limit of 64 KB.

**Torrents and Piece Length**

The Wikipedia article mentions a common piece length of 256 KB:
> piece length—number of bytes per piece. This is commonly 28 KiB = 256 KiB = 262,144 B.

For a 2 TB file that would mean 8,388,608 pieces. Blake3 digest size is 32 bytes, resulting in at least 256 MB of hash data.
A 2 GB file would require 256 KB, which is still substantial when we are considering the target block size (which is smaller is better and should fit in a single UDP packet).

Interesting related discussion: https://www.reddit.com/r/torrents/comments/dzxfz1/2019_whats_ideal_piece_size/

https://wiki.vuze.com/w/Torrent_Piece_Size mentions "All in all, a torrent should have around 1000-1500 pieces" providing this table:
![image](https://user-images.githubusercontent.com/13511064/139002174-10a57b5a-e2ca-4319-ae81-19c44cafc489.png)

**Comment by Akilan1999** [comment]
# Peernet Swarming Proposal 


## Introduction 

To investigate various methods to achieve downloading a chunk of files from various nodes and  to ensure choking is handled. We will look at the techniques the bittorrent protocol follows and other methods which could be used to ensure when we can download chunks in sequence to ensure a user can stream a video while a file gets downloaded. The major decision would be to decide what would be the chunk size of the files.

## Background 
Here we would talk about the various concepts used by the bittorrent protocol to ensure we can choose the best available to implement peernet swarming. 

### Pieces length
The number of bytes per piece.
The piece’s length must be a power of two and at least 16KiB.

### The Piece Selection Algorithm of BitTorrent
One of the largest questions in BitTorrent is “what pieces should I select to download?”
With a traditional client-server model, we download the whole file. But now, we get to pick what pieces to download.
The idea is to download the pieces that no one else has - the rare pieces. By downloading the rare pieces, we make them less rare by uploading them. TCP does this because if we send 16 connections at once, the server may not be used to the traffic and congestion will happen on the network.
If we’re not regularly sending data, TCP may cap our network connection at a slower speed than normal.
BitTorrent makes sure to always send data by breaking pieces down into further sub-pieces.
Each sub-piece is about 16KB in size. The size for a piece is not fixed, but it is somewhere around 1MB.
The protocol always has some number of requests (five) for a sub-piece pipe-lined. When a new sub-piece is downloaded, the client sends a new request. This helps speed things up.

### Strict Policy
Once the BitTorrent client requests a sub-piece of a piece, any remaining sub-pieces of that piece are requested before any sub-pieces from other pieces.

### Rarest First
The main policy in BitTorrent is to pick the rarest first. We want to download the piece which the fewest other peers own.
This is so we can make it ‘un-rare’. If only one peer has a piece and they go offline, no one will get the complete file.
A plethora of benefits exist for this policy.

### Growing the seed
Rarest first makes sure that we download only new pieces from the seed.
The seed will begin as a bottleneck. The one peer with the file.
A downloader can see what pieces their peers possess, and the rarest first policy will cause us to fetch the pieces from the seed which have not been uploaded by other peers.

#### Increased download speed
The more peers that hold the piece, the faster the download can happen. This is because we can download sub-pieces from other peers.

#### Enable uploading
A rare piece is most wanted by other peers and getting a rare piece means peers will be interested in uploading from us. As we will see later, the more we upload, the more we can download.
#### Most common last
It is sensible to leave the most common pieces to the end of the download. As many peers hold common pieces, the probability of being able to download them is much larger than that of rare pieces.
#### Prevent rarest piece missing
When the seed dies, all the different pieces of the file should be distributed somewhere among the remaining peers.
####  Random First Piece
Once we download, we have nothing to upload. We need the first piece, fast. The rarest first policy is slow. Rare pieces are downloaded slower because we can download its sub-pieces from only a few peers.

### Endgame Mode
Sometime’s a peer with a slow transfer rate will try to give us a sub-piece. Causing a delay of the download. To prevent this, there is “endgame mode”.
Remember the pipe-lining principle? There are always several requests for sub-pieces pending.
We are downloading from 2 peers, there is 1 other peer we are not downloading from.
When all the sub-pieces a peer lacks are requested, they broadcast this request to all peers. This helps us get the last chunk of the file.
If a peer has the missing sub-piece, they will send that back to our computer.
Once a sub-piece arrives, we send a cancel-message telling the other peers to ignore our request.

### Resource Allocation Using Tit-For-Tat
No centralised resource allocation in BitTorrent exists. Instead, every peer maximises their download rate.
A peer will download from whoever they can. To decide who to upload to, they will use a variant of the “tit-for-tat” algorithm.
The tit-for-tat strategy comes from game theory. The essence is:
“Do onto others as they do onto you”
On the first move, cooperate
On each succeeding move do what your opponent did the previous move
Be prepared to forgive after carrying out just one act of retaliation

### The Choking Algorithm
Choking is a temporary refusal to upload to another peer, but we can still download from them.

To cooperate peers upload, and to not cooperate they “choke” the connection to their peers. The principle is to upload to peers who have uploaded to us.

![image](https://user-images.githubusercontent.com/31743758/142470263-2d7610f2-f644-4392-a414-40339700eea7.png)

We want several bidirectional connections at the same time and to achieve Pareto Efficiency.
We consider an allocation Pareto Efficient if there is no other allocation in which some individual is better off and no individual is worse off.
Thus the big question is how to determine which peers to choke and which to unchoke?
A peer always unchokes a fixed number of its peers (the default is 4).
Current download rates decide which peers to unchoke. We use a 20-second average to decide this. Because of the use of TCP (slow-start) , rapidly choking and unchoking is bad. Thus, this is calculated every 10 seconds.
If our upload rate is high more peers will allow us to download from them. This means that we can get a higher download rate if we are a good uploader. This is the most important feature of the BitTorrent protocol.
The protocol prohibits many “free riders” which are peers who only download and don’t upload.
For a peer-to-peer network to be efficient, all peers need to contribute to the network.

### Anti-Snubbing
What happens if all peers uploading to another peer decide to choke it? We then have to find new peers, but the optimistic unchoking mechanism only checks one unused connection every 30 seconds. To help the download rate recover more, BitTorrent has snubbing.
If a client hasn’t received anything from a particular peer for 60 seconds, it will presume that it has been ‘snubbed’.
Following the mentality of tit-for-tat, we retaliate and refuse to upload to that peer (except if they become an optimistic unchoke).
The peer will then increase the number of optimistic unchokes to find new connections quicker.

### Tumbling window of piece selection 
![image](https://user-images.githubusercontent.com/31743758/142470417-08d65c2e-600f-4712-a5f9-627e1083a314.png)

Figure 5 
When scheduling the piece, there is a mechanism of TorrentPieceScheduler used to manage the piece priority. This scheduler uses a tumbling window to schedule the piece in a certain time duration. We can see in Figure 5, the scheduling will apply for piece number 1 and 2 as the top priority while piece number 3 and 4 are lower priority. When the piece in the first phase has been downloaded, the download will further continue with piece number 3 and 4 as the top priority and piece number 5 and 6 as the lower one. This mechanism will work continuously until all of the pieces in the video file have been downloaded.

**Comment by Kleissner** [comment]
We should move your Peernet Swarming Proposal into a separate issue to keep this issue clean and maintain the overview.
The strategy of exchanging fragments (and joining/leaving swarms) is independent/separate from the file fragmentation.
